version: "3.7"

services:
  ejabberd:
    restart: unless-stopped
    hostname: ejabberd
    container_name: ejabberd
    image: sando38/docker-ejabberd-multiarch
    user: 999:999
    ports:
      - 80:5280 # http
      # - 3478:3478 # STUN/TURN non-tls
      # - 3478:3478/udp # STUN/TURN non-tls
      - 5222:5222 # xmpp-client
      # - 5223:5223 # xmpp-client TLS
      # - 5269:5269 # xmpp-server
      # - 5270:5270 # xmpp-server TLS
      - 5443:5443 # https
      # - 5349:5349 # STUN/TURN TLS
      # - 49152-49300:49152-49300/udp # TURN range
    env_file:
      - ejabberd.env
    # environment:
    #   - ACME_ENABLED=false # default 'auto'
    volumes: # directories must be own by ejabberd user 999:999
      - config:/home/ejabberd/etc/ejabberd     # for configuration files
      - data:/home/ejabberd/var/lib/ejabberd   # mnesia database & acme client certificates
      - http-files:/home/ejabberd/files        # for HTTP fileserver functionality
      - http-upload:/home/ejabberd/upload      # for HTTP upload functionality
      - tls:/home/ejabberd/tls                 # for custom tls certicates
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  config:
  data:
  http-files:
  http-upload:
  tls:
