version: "3.7"

# secrets: # should be owned by ejabberd user:group (9000:9000)
#   ldap_bind_pw:
#     file: /path/to/ldap_bind_pw
#   db_password:
#     file: /path/to/db_password
#   redis_password:
#     file: /path/to/redis_password

services:
  ejabberd:
    restart: unless-stopped
    hostname: ejabberd
    container_name: ejabberd
    image: sando38/docker-ejabberd-multiarch # this compose example works from version 3.0.0 onwards
    user: 9000:9000
    ports:
      - 80:5280 # http
      # - 3478:3478 # STUN/TURN non-tls
      # - 3478:3478/udp # STUN/TURN non-tls
      - 5222:5222 # xmpp-client
      # - 5223:5223 # xmpp-client TLS
      # - 5269:5269 # xmpp-server
      # - 5270:5270 # xmpp-server TLS
      - 5443:5443 # https
      # - 5349:5349 # STUN/TURN TLS
      # - 49152-49300:49152-49300/udp # TURN range
    env_file:
      - ejabberd.env
#     environment:
#       - LDAP_BIND_PW_FILE=/run/secrets/ldap_bind_pw
#       - DB_PASSWORD_FILE=/run/secrets/db_password
#       - REDIS_PASSWORD_FILE=/run/secrets/redis_password
#     secrets:
#       - ldap_bind_pw
#       - db_password
#       - redis_password
    volumes: # directories must be owned by ejabberd user 9000:9000
      - config:/opt/ejabberd/conf          # for configuration files
      - data:/opt/ejabberd/database        # mnesia database & acme client certificates
      - http-files:/opt/ejabberd/files     # for HTTP fileserver functionality
      - http-upload:/opt/ejabberd/upload   # for HTTP upload functionality
      - tls:/opt/ejabberd/tls              # for custom tls certicates
#       - /path/to/erlang-cookie:/opt/ejabberd/.erlang.cookie
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
#     read_only: true

volumes:
  config:
  data:
  http-files:
  http-upload:
  tls:
