namespace: xmpp
bases:
  - ../../bases
#nameSuffix: '-xmpp'
secretGenerator:
- name: ejabberd-secrets
  env: configs/secrets.env
- name: erlang-cookie
  files:
  - configs/.erlang.cookie
configMapGenerator:
#- name: ejabberd-config
#  files:
#  - configs/ejabberd.yml
#- name: mod-cron-config
#  files:
#  - configs/mod_cron.yml
- name: ejabberd-env
  env: configs/variables.env
#patchesStrategicMerge:
#  - mod_cron.yaml
#  - erlang-cookie.yaml
resources:
  - ingressroute-http-acme.yaml
  - ingressroutetcp.yaml
images:
- name: sando38/docker-ejabberd-multiarch
  newTag: "v22-05-v3.0.0"
