namespace: xmpp
bases:
  - ../../bases
#nameSuffix: '-xmpp'
secretGenerator:
- name: ejabberd-secrets
  env: configs/secrets.env
#configMapGenerator:
#- name: ejabberd-config
#  files:
#  - configs/ejabberd.yml
#- name: mod-cron-config
#  files:
#  - configs/mod_cron.yml
- name: ejabberd-env
  env: configs/variables.env
#patchesStrategicMerge:
#  - mod_cron.yaml
resources:
  - ingressroute-http-acme.yaml
  - ingressroutetcp.yaml
images:
- name: sando38/docker-ejabberd-multiarch
  newTag: "v21-12-v2.1.0"
