apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ejabberd-upload
  namespace: xmpp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
